### ISSUE TITLE
Thumbnail: 404 for PDF imported using API (digitalobjectsCreateAction)

### ISSUE THREAD

**Issue by dersmon** [artefactual/atom#1065]
We get broken image paths after having imported some PDFs using the API. Our request data payload looks like this (python):

```python
{
        'information_object_slug': obj.metadata['atom_id'],
        'media_type': 'text',
        'mime_type': 'application/pdf',
        'uri': f"{repository_uri}/file/{obj.id}/data/pdf/{obj.id}.pdf",
        'name': f"{obj.id}.pdf"
}
```
Where 'uri' is an external link where the PDF document is located. Clicking on "Open original digital object" in atom's interface works - it is just the thumbnail that is broken (or non-existent?).

**Comment by fiver-watson** [comment]
Hi @dersmon , I will ask our team to look into this report. In the meantime, if the thumbnail is missing or broken in AtoM, you could use the regen-derivatives task to address that. See: 

* https://www.accesstomemory.org/docs/latest/admin-manual/maintenance/cli-tools/#regenerating-derivatives

**Comment by dersmon** [comment]
Hi @fiver-watson , I just ran `php symfony digitalobject:regen-derivatives`, then `php symfony cc && php symfony search:populate` for good measure, but the problem persists.

**Comment by fiver-watson** [comment]
Hi @dersmon  - is it just the PDFs causing this issue?

If so, you might be running into the following issue, caused by a change in ImageMagick. Please see this thread for more information and a solution:
 
* https://groups.google.com/d/msg/ica-atom-users/AwNUifxWsS4/BvfV6x9uBQAJ

Once you have this fix in place, you can try the derivatives regeneration task again to see if it resolves the issue.

**Comment by dersmon** [comment]
Hi @fiver-watson in the end it seems the 404 was caused by our server setup.
