### ISSUE TITLE
Ubuntu 20.04 PHP 7.4

### ISSUE THREAD

**Issue by bert-willekens** [artefactual/atom#1267]
Hi

The current LTS release for Ubuntu is 20.04. Because of the LTS status I followed your Ubuntu 18.04 guide.
Currenty PHP version is 7.4 and the first issue I've found is about strings with curly brackets substrings. This specific error seems easy to fix.

````
2021/03/18 21:05:07 [error] 1692#1692: *1 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /usr/share/nginx/atom/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/system/io/UnixFileSystem.php on line 78PHP message: PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /usr/share/nginx/atom/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/system/io/UnixFileSystem.php on line 79PHP message: PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /usr/share/nginx/atom/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/system/io/UnixFileSystem.php on line 91PHP message: PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /usr/share/nginx/atom/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/system/io/UnixFileSystem.php on line 112PHP message: PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /usr/share/nginx/atom/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/system/io/UnixFileSystem.php on line 125PHP message: PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /usr/share/nginx/atom/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/system/io/UnixFileSystem.php on line 143PHP message: PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /usr/share/nginx/atom/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/system/io/UnixFileSystem.php on line 157PHP message: PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /usr/share/nginx/atom/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/system/io/UnixFileSystem.php on line 197PHP message: PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /usr/share/nginx/atom/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/tasks/s
2021/03/18 21:05:07 [error] 1692#1692: *1 upstream sent too big header while reading response header from upstream, client: 192.168.149.66, server: _, request: "GET /index.php/sfInstallPlugin/insertSql HTTP/1.1", upstream: "fastcgi://unix:/run/php7.4-fpm.atom.sock:", host: "192.168.141.33", referrer: "http://192.168.141.33/index.php/sfInstallPlugin/configureDatabase"
````

**Comment by fiver-watson** [comment]
Hi @bert-willekens, 

Thanks for this report - we're working on it! Ubuntu 20.04 and PHP 7.4 are not officially supported for AtoM 2.6 and earlier, but we're ensuring that they will be for release 2.7. 

With this particular issue, I think we have a fix coming in the upcoming 2.6.3 release, in preparation for 2.7. Please see the following related ticket in our issue tracker: 

* https://projects.artefactual.com/issues/13433

Our latest Vagrant development environment (v27.0.01 per [this list](https://app.vagrantup.com/artefactual/boxes/atom)) is deployed against our qa/2.x branch using 20.04 and PHP 7.4, so we can try to find and fix any compatibility issues as we carry on with feature development and bug fixes. If you're interested in helping us to find further issues, we have instructions on configuring vagrant here: 

* https://www.accesstomemory.org/docs/latest/dev-manual/env/vagrant/

Thanks again for the report! For now I'm going to close this issue, since it seems to match the one we already have in our issue tracker. 

Cheers, 

Dan Gillean, MAS, MLIS
AtoM Program Manger
Artefactual Systems

**Comment by bert-willekens** [comment]
Hi @fiver-watson! Thanks for all the info. Will you support do-release-upgrade after upgrading 2.6 to 2.7(.x) once 20.04 is supported?

**Comment by fiver-watson** [comment]
Hi again @bert-willekens  - sorry for the delay in replying. 

do-release-upgrade will likely work for upgrading the base operating system - however, we don't officially support or test this method, since many of the underlying dependencies change between major releases, and upgrading Ubuntu in place may require a lot of system cleanup to ensure that it matches expectations. As noted in our conversation above, other libraries and extensions will require updates (as with the PHP version) and in some cases this may not match the supported defaults of the OS version - for example, PHP 7.4 is the default PHP version installed in Ubuntu 20.04, but there's a chance that we will focus on PHP 8 support for the 2.7 release (still to be determined - ideally we will maintain backwards compatibility with 7.4). 

All this to say: yes, it could work, but we will not explicitly promote this method, and may not be able to provide detailed support to our user community who choose to upgrade this way, where there are further upgrades, cleanups, or incompatibilities needing resolution to be addressed.
