### ISSUE TITLE
Feature: Command line tool for renaming slugs

### ISSUE THREAD

**Issue by anvit** [artefactual/atom#1609]
Having a command line tool to rename slugs (say something like `php symfony tools:rename-slug  old_slug_name new_slug_name`)
can speed up things for users who want to batch rename them using a shell script, and don't want to manually update them one at a time using the UI or run SQL queries.

**Comment by fiver-watson** [comment]
@anvit if you develop this tool, i would recommend that you also consider something like a `--csv` option. When used, instead of the input being individual before and after slug values, it is a file path to a CSV with 2 columns - `oldSlug` and `slug` (or similar). That way the task can be used for selective bulk updates, regardless of entity type

**Comment by anvit** [comment]
@fiver-watson Oh, that's a good idea! That would make things much easier for a lot of folks who want to bulk update slugs!
