### ISSUE TITLE
Feature: show a Bootstrap 2 deprecation notice in the web UI

### ISSUE THREAD

**Issue by djjuhasz** [artefactual/atom#1642]
Display a notice in the AtoM web user interface to notify administrators of the future deprecation of the Bootstrap 2 themes (Dominion and ArchivesCanada) and derivative custom themes and the need to switch to a Bootstrap 5 theme.  Displaying a notice in the UI would inform administrators that have not read about the deprecation in the user forum or release notes.

Design considerations:
- Where should the notice be displayed? It could be displayed at the top of the page like the new release notice and GDPR notice, but this could result in 3 notices being shown at the same time.
- Who should see the notice? I don't see any benefit to notifying public (non-authenticated) users, but I'm not sure if only administrators should see it, or if editors, translators, etc. should see it as well.  As the regular users of the software, an editor or translator will likely see the notice before an administrator.
- When should the notice be displayed? Displaying the notice every time a user logs will probably be annoying, so maybe it should only be shown once per user?
- What information should be put in the notice? Linking to a guide on upgrading a theme to Bootstrap 5 would probably be helpful for many administrators.

**Comment by anvit** [comment]
Here's a potential deprecation notice banner I've put together. 


- I'm still thinking of keeping it in the header still, because it still makes the most sense for this sort of a message to be shown at the very top, but I'm changing the alert styles a little bit to visually distinguish this one from the other two.  

![Bootstrap 2 Deprecation Banner](https://github.com/artefactual/atom/assets/2498062/d689a743-a8f0-4782-ab90-7e714a688987)

Also given that the notices go away once they are dismissed, seeing all of them at once would likely be rare, and should be at most a one-time annoyance.

I'm also thinking of making this notice sticky so that it stays at the top unlike the other two until it is dismissed.

![Deprecation banner featuring sticky styles](https://github.com/artefactual/atom/assets/2498062/148c9ca2-d02d-4bc0-88a2-572d5604130d)

- This is the message I've come up with for now, and the link will point to a docs page that details how to change/upgrade themes.
- Agreed, it makes sense to show this to all authenticated users, as they would likely be able to bring it to the attention of admins quickly.
- Also agreed that it should be only shown once per user.

@djjuhasz (or anyone who has suggestions/opinions really) let me know if you have any feedback for me!

**Comment by djjuhasz** [comment]
@anvit nice, those screenshots good to me.  I find the dark red quite intense and I think it might be a bit too alarming for a deprecation notice - but maybe it's good that it's hard to ignore. :)  I would suggest changing the color of the "More info" link too, to make it clear that it is a link.

I like the positioning and the text, and the sticky header is cool.

**Comment by anvit** [comment]
I've updated the link colour and added the underline just to make it clear that it is a link (also double checked that the contrast ratio falls within WCAG guidelines):
![Updated deprecation banner](https://github.com/artefactual/atom/assets/2498062/bbd4d765-d81e-47d9-802c-11e46131f502)

I'm kinda split on the intense red colour too though. On one hand, this is kind of an urgent notice, but on the other, it's pretty hard to ignore a full width banner on the page and maybe it doesn't need to be quite as loud. I'll wait and see what other folks think.

**Comment by fiver-watson** [comment]
Given that there's a BS5 theme already in AtoM, i might suggest changing the word "updating" (which sounds a lot like "upgrading" and may lead to confusion) to something more neutral, like "switching" ?

Will this banner NOT show if the user is using the BS5 theme? And, will BS5 be the default installation theme in 2.8? 

I could go either way, but kind of agree that if the banner is sticky and must be manually dismissed, then I don't know if the color red needs to be quite so vivid / alarming... 

Overall, looks great!

**Comment by djjuhasz** [comment]
@anvit I :heart: the new link colour. :)

**Comment by anvit** [comment]
How does this version look @djjuhasz @fiver-watson? 

I updated the message, and yes, BS5 will be the default theme for new installations in 2.8, and this message will only be shown to those using BS2 themes.

![Deprecation banner with less intense background and updated message](https://github.com/artefactual/atom/assets/2498062/c8e58a53-2953-4e91-8cc9-1d9452eaf973)

**Comment by fiver-watson** [comment]
:+1:  Looks great to me! Nicely done :)

**Comment by djjuhasz** [comment]
Agreed! Looks good. :+1:

**Comment by jraddaoui** [comment]
Doing the code review, just adding a comment here. I think it's okay to show this to editors and translators alongside admins, but not to ALL authenticated users.
