### ISSUE TITLE
Problem: Access Copies links don't always link properly.

### ISSUE THREAD

**Issue by melaniekung** [artefactual/atom#1744]
### Current Behavior

Thumbnail and Reference Copy links aren't accurate when site is hosted on path instead of domain.

### Expected Behavior

Example Scenario:
website url: example.com/atom
current copy link: example.com/path/to/link
desired copy link: example.com/atom/path/to/link

**Comment by melaniekung** [comment]
**Status:** PR ready but awaiting for test env from #support-request for testing.

**Comment by anvit** [comment]
Marking this as a `wont fix` and closing this for now. AtoM installations are recommended to be on its own domain/subdomain instead of a sub-folder, but it should be possible to have a workaround for this by configuring the web server appropriately. Feel free to re-open if there are still issues with the links with an appropriate AtoM and web server configuration.
