### ISSUE TITLE
Impossible to generate reports

### ISSUE THREAD

**Issue by pprw** [artefactual/atom#661]
When I try to export a report (box label or physical location) for a "file", I have these messages in the job manager:

`Job 525 "arGenerateReportJob": No results found for Étiquette de boîte report.`

or

`Job 519 "arGenerateReportJob": No results found for Localisations physiques report.`

And no report are generated.

Obviously my installation is in French. I have no problem to export the list of file of a fonds *but* the html/csv output does not contain the location information and this information is present.

worker log:
```
2018-02-06 05:10:08 > New ability: arFindingAidJob
2018-02-06 05:10:08 > New ability: arInheritRightsJob
2018-02-06 05:10:08 > New ability: arObjectMoveJob
2018-02-06 05:10:08 > New ability: arInformationObjectCsvExportJob
2018-02-06 05:10:14 > Ability not defined: qtSwordPluginWorker. Please ensure the job is in the lib/task/job directory or that the plugin is enabled.
2018-02-06 05:10:14 > New ability: arUpdatePublicationStatusJob
2018-02-06 05:10:14 > New ability: arFileImportJob
2018-02-06 05:10:14 > New ability: arInformationObjectXmlExportJob
2018-02-06 05:10:14 > New ability: arXmlExportSingleFileJob
2018-02-06 05:10:14 > New ability: arGenerateReportJob
2018-02-06 05:10:14 > New ability: arActorCsvExportJob
2018-02-06 05:10:14 > New ability: arActorXmlExportJob
2018-02-06 05:10:14 > New ability: arRepositoryCsvExportJob
2018-02-06 05:10:14 > Running worker...
2018-02-06 05:10:14 > PID 18191
2018-02-06 10:11:34 > Job started.
/sites/xxxxxxx/downloads/reports2018-02-06 10:11:34 > No results found for Étiquette de boîte report.
2018-02-06 10:11:34 > Job finished.
```

**Comment by fiver-watson** [comment]
Hi there! Thank you for this report, @pprw . I have reproduced this locally, and filed the following ticket in our issue tracker, which we use instead of GitHub issues: 

* https://projects.artefactual.com/issues/11961

Please note that as an open source project managed by a company that gives away its core resources, we rely on community support to prioritize and sponsor fixes and enhancements for inclusion in the next public release. You can read more about our development philosophy and business model on our wiki, here: 

* https://wiki.accesstomemory.org/Development/Philosophy

So, while we now have a ticket to track this issue, and I have added it to an internal list of bugs to review and try to address in the next release, this does not guarantee its inclusion. If this is a priority issue for you or your institution and you would like to sponsor a fix for it so we can include it in our upcoming 2.4.1 bug fix release, let me know and our team can prepare a development estimate for you.

If you are a developer and would like to address this issue yourself and share the fix back with the community, we welcome pull requests! We have a number of development resources to get you started, here: 

* https://wiki.accesstomemory.org/Development#Development_resources

I'm going to close this GitHub issue now, so we can continue tracking this ticket in our Issue Tracker. Thank you again for the report! 

Regards, 

Dan Gillean, MAS, MLIS
AtoM Program Manager
Artefactual Systems, Inc.

**Comment by pprw** [comment]
Thanks! The bug report you created focuses on the missing storage location information. In my atom instance, this information is missing when I create a report of the list of file of a fonds. 

It is also impossible to generate reports for file's level (or item's level). This is a more critical bug because the location information is not only missing, there is no report at all. The two reports possible (Box Label or storage location) are not created at all. I just have the error message "No results found for Étiquette de boîte report" or " No results found for Localisations physiques report."  in the job worker log. 

The translation bug prevents the creation of reports in these cases. We could think switching temporary the site in English will fix the issue and create (English) reports. But in my experience, after switching the site in English with the button dedicated, I have a 500 error for every report creation attempt.

We personally don't have the possibility to finance development but I hope this issue will be fixed some day for the sake of all non-English users.

**Comment by fiver-watson** [comment]
Oh! Thank you for this additional information. I will do some further testing, and will either expand the scope of the ticket, or create a few related tickets to better capture the core issues. More soon.

**Comment by fiver-watson** [comment]
Hi again @pprw, 

I'm doing a bit more testing. So far, as described on the issue I created, the box label and storage locations report generated for me, but with missing information. I had no problem generating file and item reports - they worked for me as expected. 

I will need a bit more information from you to support my testing. Can you please tell me more about your particular installation? Specifically, things like: 

* What version of AtoM do you have installed - can you provide the full version number visible in Admin > Settings > Global at the top of the page?
* Did you follow our recommended installation instructions? 
* If yes, are you installed using Ubuntu 16.04 or 14.04? If no, what changes have you made?
* Is the default installation culture of your site (visible in apps/qubit/config/settings.yml "fr"? Or something else?
* Were the descriptions created while using the French user interface, or was the language menu flipped to something else when they were created?
* Anything else you can tell me that you think will assist in recreating this issue is welcome! 

I did notice in your original report that one ability (for the qtSwordPlugin was skipped. I don't think it should matter, but can you try something for me first?

1. Navigate to Admin > Plugins and make sure that the qtSwordPlugin is enabled
2. In the command-line of your application, in the root AtoM directory (which is `/usr/share/nginx/atom` if you followed our installation instructions) first let's clear any running jobs - NOTE this will kill any jobs currently in the queue, so if you have running jobs, you might want to let them complete first: 

* `php symfony jobs:clear`

3. Now let's clear our application cache: 

* `php symfony cc`

4. We want to restart the atom-worker and other related services next. 

If you are using Ubuntu 14.04 with PHP 5.x: 
* sudo restart atom-worker
* sudo service php5-fpm restart
* sudo service memcached restart

If you are using Ubuntu 16.04 with PHP7.0:
* sudo systemctl restart atom-worker
* sudo systemctl restart php7.0-fpm
* sudo systemctl restart memcached

Let me know if this makes any difference. Thanks in advance!
