### ISSUE TITLE
Finding Aid languages not used

### ISSUE THREAD

**Issue by Surfrdan** [artefactual/atom#663]
https://github.com/artefactual/atom/blob/e535356754fb2fcb8ed7c61c68fdbbe222dc519a/lib/job/arFindingAidJob.class.php#L82

It appears that the finding aid $exportLanguage  and $sourceLanguage variables are not used in the processing of the finding aid.

**Comment by fiver-watson** [comment]
Hi @Surfrdan, thanks for pointing this out. I've let our developers know. 

We use Redmine as our primary issue tracker, so I have filed an issue ticket there, and will close this one for now. Here's the Redmine ticket: 

* https://projects.artefactual.com/issues/11963

If you would like to send us a pull request to remove this unused code, and/or refactor the finding aid generation code, we would welcome that! We have a guide to code contributions on our wiki, here: 

* https://wiki.accesstomemory.org/Development/Contribute_code

Please note the section on the [Contributor's agreement](https://wiki.accesstomemory.org/Development/Contribute_code#Copyright_and_license), which we would need you to sign to accept any PR you send to the public project. Otherwise, we'll hope to tackle this in a future release! 

Cheers, 

Dan Gillean, MAS, MLIS
AtoM Program Manager
Artefactual Systems
