### ISSUE TITLE
Import dcterms

### ISSUE THREAD

**Issue by goetzk** [artefactual/atom#814]
Hi,
It would be great to import more than just DC Elements in to atom, DC terms has a much larger set and covers many more of the ISAD fields that atom is already storing internally.

This is a Wishlist item which is already open somewhere but I couldn't find it.

**Comment by fiver-watson** [comment]
Hi @goetzk  - I couldn't find an existing wishlist ticket for this either, so I have created one here: 

* https://projects.artefactual.com/issues/12679

Consequently, I am going to close this issue, since Redmine (the system where I created the ticket linked above) is our system of record for issue tracking. 

Thanks for your suggestion!
