### ISSUE TITLE
build-nested-set error

### ISSUE THREAD

**Issue by jhennig** [artefactual/atom#831]
Got an error when building a nested set:
PDOException: SQLSTATE[HY000]: General error: trying to execute an empty query in /var/www/html/atom-2.4.1/lib/task/propel/propelBuildNestedSetTask.class.php:126
  Stack trace:
  #0 /var/www/html/atom-2.4.1/lib/task/propel/propelBuildNestedSetTask.class.php(120): PDO->exec('')

What's happening is the loop at line 117 run's 1 too many times if the row count is a multiple of 4000. 
We had exactly 84000 records and got the error above.
So I think the fix is:

for ($i=0; $i <= (count($this->rows)-1); $i+=$incr)
        {
          $sql = implode("\n", array_slice($this->rows, $i, $incr));
          $conn->exec($sql);
        }

**Comment by fiver-watson** [comment]
Hi @jhennig thank you so much for identifying this issue, letting us know, **and** providing a potential solution! 

We don't regularly use GitHub to manage issues, so I have filed a ticket in our official project tracker, here: 

* https://projects.artefactual.com/issues/12754

I will be adding this to a list of community-reported bugs we hope to address in the next public release. This is not a guarantee, however - we have a limited amount of time and resources to address bugs with each release, and the only way we can guarantee inclusion is if someone either contributes a code fix, or if an institution sponsors the work required for us to fix it. If you'd like to learn more about how we maintain and develop AtoM, see: 

*  https://wiki.accesstomemory.org/Development/Philosophy

 If you would like to **submit a pull request** to fix this issue, we would welcome that! We have some general guidelines on our wiki, here: 

* https://wiki.accesstomemory.org/Development#Development_resources

See especially the link for [contributing code](https://wiki.accesstomemory.org/Development/Contribute_code). If you have not previously done so, we would first need you to sign and submit a [contributor's agreement](https://wiki.accesstomemory.org/Development/Contribute_code#Copyright_and_license), and then open a pull request against our qa/2.5.x branch. It would be most helpful if the PR's short title included something like, "refs #12754" so the PR can easily be related back to the bug ticket I've filed based on your report. 

Let me know if you have any questions. Otherwise, we'll try to include a fix in the 2.5 release if we are able! Thanks again!
