### ISSUE TITLE
arOaiPlugin non-UTC from & until dates

### ISSUE THREAD

**Issue by rferris** [artefactual/atom#893]
Hi,

I recently came to discover that the arOaiPlugin does not convert between UTC and local time. When one uses the from and until url parameters with oai, the result will be requested from the database exactly as it was sent to Atom, where it should be converted to local time first.

Example of current behaviour (omitting dates for clarity);
I modify an object at 20:00 AEST (+10).
I make an oai request with from=09:30&until=10:30
No results are returned
I make an oai request with from=19:30&until=20:30.
OAI returns the object with the a timestamp of 10:00 

Since the OAI standard dictates that all date/times are to be in UTC, the above results are incorrect and should look more like below:

I modify an object at 20:00 AEST.
I make an oai request with from=09:30&until=10:30
OAI returns the object with a timestamp of 10:00.

A solution I have put in place was to modify the setUpdateParametersFromRequest within arOaiPluginComponent.class.php. I simply run strtotime on $request->from and $request->until and this converts the date/time to my local timezone, ready to be looked up in the database.

Cheers

**Comment by fiver-watson** [comment]
Hi @rferris thanks for filing this. Since it sounds like you have a fix in place locally, would you be interested in sending a pull request to the public project?

If yes, I'm including a few links and resources below. 

First, please take a look at t[his page](https://wiki.accesstomemory.org/Development/Contribute_code), and if you'd like to send a pull request, please fill out the contributor's agreement ([PDF link here](https://wiki.accesstomemory.org/images/9/9d/Accesstomemory-contributor-agreement-2014.pdf)) and send it to us at agreement@artefactual.com. There are further pointers in that page for submissions as well. 

Generally, to be able to track all changes in AtoM over time, we like to relate our PRs to tickets in our issue tracker. I've created a ticket here: 

* https://projects.artefactual.com/issues/13025

You can reference it in your PR title - for example, "Convert local time to UTC in OAI requests, refs #13025"

For larger PRs we have some further suggestions on our wiki [here](https://wiki.accesstomemory.org/Development/Recommendations) but for this I don't think you'll need to worry. 

We are putting new features and enhancements in our qa/2.6.x branch, so if you do submit a PR, please be sure to rebase your branch and submit the PR against qa/2.6.x! 

Thanks!

**Comment by rferris** [comment]
Contributor agreement signed and PR submitted. 👍

**Comment by fiver-watson** [comment]
A fix for this, provided by @rferris , was merged into AtoM's qa/2.6.x branch in https://github.com/artefactual/atom/commit/c78ab91a37c8bf15fdca43c4360c185ce7e446ea

Closing this issue now - thanks again for your contribution!
