### ISSUE TITLE
Versions in Docker-compose get left behind when a 'qa/.x' branch is renamed or deleted, e.g. qa/2.5.x becomes stable/2.5.x

### ISSUE THREAD

**Issue by ricardodepinho** [artefactual/atom#901]
https://github.com/artefactual/atom/blob/cefd4f9b59e8d93c16f0b6b8e5625e875f0dc80c/docker/Dockerfile#L3

**Comment by ross-spencer** [comment]
@ricardodepinho just trying to build this myself this morning too and spotted the same thing. I hope you don't mind but I amended the original title to try and capture the broader issue. 

My particular case is I want to be able to run `qa/2.6.x` and so that would require two Dockerfile changes per release/branch-rename if I understand the issue correctly.

**Comment by ricardodepinho** [comment]
@ross-spencer I suppose you didn't get it right! 
When releasing the stable/2.5.x branch someone forgot to change this GIT_BRANCH reference to it.
If you clone the stable/2.5.x and try to build docker-compose with this docker file, it tries to get the TAR from where it doens't exists any more!
https://github.com/artefactual/atom/archive/$GIT_BRANCH.tar.gz 
Some one at Artefactual should correct this for the docker-compose to build correctly.
I've tested with " ARG GIT_BRANCH=stable/2.5.x " and it works just fine!

**Comment by ross-spencer** [comment]
It does look that way :wink:. I am using the same work-around, the good news is we've some smart folks looking at the possibilities for a more sustainable configuration for the Docker environment. It might be a short while away, so folks are advised to consider making this same change to the Docker line until then: https://github.com/artefactual/atom/blob/cefd4f9b59e8d93c16f0b6b8e5625e875f0dc80c/docker/Dockerfile#L3

**Comment by ricardodepinho** [comment]
Let's keep hope on those smart folks!! ;-)

**Comment by jraddaoui** [comment]
Hi @ricardodepinho and @ross-spencer,

Thanks for reporting and discussing this problem. It has been a while, but we finally had some time to upgrade the Docker environment.

In the changes from 9fa52d2, we have removed the `GIT_BRANCH` argument and the build process will now copy the entire project folder in its current status instead of fetching a tarball from Github using that argument. There are other minor upgrades and changes in that commit if you want to give them a try before we close this issue.

There is also an [in-progress pull request](https://github.com/artefactual/atom-docs/pull/121) with minor changes to the documentation.
