### ISSUE TITLE
PHP 7.3 compatibility?

### ISSUE THREAD

**Issue by jcharaoui** [artefactual/atom#970]
Hello, I'm considering deploying AtoM on a Debian 10 machine, which ships with PHP 7.3 instead of PHP 7.2 as recommended in the installation docs. Should I expect any issues due to this? Thanks.

**Comment by fiver-watson** [comment]
Hi @jcharaoui, we have not yet tested AtoM with PHP 7.3. However, based on the breaking changes introduced in 7.0 and 7.1 and the changes we had to make to support PHP 7.2, I would not be surprised if there were some issues. 

If you decide to proceed, let us know how it goes and what you discover! Otherwise, to ensure you have a working installation, we recommend downgrading to PHP 7.2 for now.

**Comment by jcharaoui** [comment]
Thanks for the quick answer! I'll test with PHP 7.3 and report any issues!
